name: eslint-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
      - name: install dependencies
        run: make -C frontend install
      - name: run Eslint
        run: make lint-frontend